### ISSUE TITLE
RFC_UNKNOWN_ERROR 28 - Unknown error in lower level library

### ISSUE THREAD

**Issue by igorpocta** [SAP/PyRFC#215] opened 2021-01-12 19:28 UTC
Hi,

I often get this RFC error. It happens randomly, I would say under the stress of the application (multiple requests at once in separate threads).

The same error occurs here: https://github.com/SAP/node-rfc/issues/128

I have this stack
pyrfc-2.0.2
python 3.7.6
rfcexec/startrfc file version 7530.500.29.40269
```
RFC_UNKNOWN_ERROR (rc=28): key=, message=Unknown error in lower level library [MSG: class=, type=, number=, v1-4:=;;;]
exception calling callback for <Future at 0x1fe7e6e7948 state=finished raised ExternalRuntimeError>
Traceback (most recent call last):
  File "C:\Users\Igor\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Development\WITTE_Nejdek\SP3_Forwarder\model\broker\sap_rfc\sap_rfc.py", line 27, in __internal_call
    result = conn.call(fm, **data)
  File "src\pyrfc\_pyrfc.pyx", line 422, in pyrfc._pyrfc.Connection.call
  File "src\pyrfc\_pyrfc.pyx", line 259, in pyrfc._pyrfc.Connection._error
pyrfc._exception.ExternalRuntimeError: RFC_UNKNOWN_ERROR (rc=28): key=, message=Unknown error in lower level library [MSG: class=, type=, number=, v1-4:=;;;]
```

**Script is simple**

```python
from config import Config
from pyrfc import Connection, ABAPApplicationError, ABAPRuntimeError, LogonError, CommunicationError, RFCError

# Create connection options to the SAP
params_connection = {
    'user': Config["SAP"]["username"],
    'passwd': Config["SAP"]["password"],
    'ashost': Config["SAP"]["hostname"],
    'lang': Config["SAP"]["language"],
    'sysnr': Config["SAP"]["system"],
    'client': Config["SAP"]["client"],
}

# Create connection
conn = Connection(**params_connection)
print(conn.version)

def call(fm: str, data: dict):
    try:
        if conn.alive != False:
            conn.reopen()

        result = conn.call(fm, **data)

        if isinstance(result, dict):
            print("RFC: Data from %s sent / received" % fm)
            return result
        else:
            print("RFC: Problem with FM: %s" % fm)
            print("received data error", str(result))
            raise

    except CommunicationError:
        print("Could not connect to server.")
        raise
    except LogonError:
        print("Could not log in. Wrong credentials?")
        raise
    except (ABAPApplicationError, ABAPRuntimeError):
        print("An error occurred.")
        raise
    except RFCError:
        print("An error occurred.")
        raise
```

**Comment by bsrdjan** [comment] 2021-01-14 10:22
The root cause of https://github.com/SAP/node-rfc/issues/128 was the bug in Connection Pool, leading to conflicts because the access to the same client connection was not synchronised among concurrent tasks.

The PyRFC does not provide the Connection Pool and PyRFC application should take care of synchronisation, which is probably the cause of errors you are getting.

The `conn.reopen()` statement at the beginning of your script made me think the reason for that was that the connection was sometimes closed, although the new connection is instantiated open. Was that the case? Your script is not closing the connection explicitly and it must be another thread closing it. That leads to conflicts because that conflicting "closing thread" can also close the connection later, during `result = conn.call(fm, **data)` and the `reopen()` can't fix that.

I can't be sure without knowing how the `call()` function is called by concurrent tasks (could you please share also that example?) but you can try following:

```python
from config import Config
from pyrfc import Connection, ABAPApplicationError, ABAPRuntimeError, LogonError, CommunicationError, RFCError

# Create connection options to the SAP
params_connection = {
    'user': Config["SAP"]["username"],
    'passwd': Config["SAP"]["password"],
    'ashost': Config["SAP"]["hostname"],
    'lang': Config["SAP"]["language"],
    'sysnr': Config["SAP"]["system"],
    'client': Config["SAP"]["client"],
}

def call(fm: str, data: dict):
    try:
        # Create connection
        conn = Connection(**params_connection)
        print(conn.version)

        result = conn.call(fm, **data)

        conn.close()

        if isinstance(result, dict):
            print("RFC: Data from %s sent / received" % fm)
            return result
        else:
            print("RFC: Problem with FM: %s" % fm)
            print("received data error", str(result))
            raise

    except CommunicationError:
        print("Could not connect to server.")
        raise
    except LogonError:
        print("Could not log in. Wrong credentials?")
        raise
    except (ABAPApplicationError, ABAPRuntimeError):
        print("An error occurred.")
        raise
    except RFCError:
        print("An error occurred.")
        raise
```

The client connection instance is moved inside the function, not accessible by other threads. It is also explicitly closed, not a must but for any case.

**Comment by bsrdjan** [comment] 2021-02-11 11:28
Hi @igorpocta, please feel free to reopen if questions still open.

**Closed** 2021-02-11 11:28 UTC
Labels: question

**Comment by Cyllenea** [comment] 2021-02-11 11:43
Thanks for the info. Finally, I used SAP Web Services.

**Comment by igorpocta** [comment] 2021-02-11 11:43
Thanks for the info. Finally, I used SAP Web Services.
