### ISSUE TITLE
ImportError: DLL load failed while importing _pyrfc: The specified module could not be found.

### ISSUE THREAD

**Issue by M9T** [SAP/PyRFC#152] opened 2019-12-16 16:20 UTC
System: Windows 10
I met a problem during importing pyrfc although I have installed SAPNWRFC before.

```
(v_rfc) C:\Users\...\rfc\assets>python
Python 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyrfc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\maebert\AppData\Local\Programs\Python\Python38\lib\site-packages\pyrfc\__init__.py", line 40, in <module>
    from pyrfc._pyrfc import (
ImportError: DLL load failed while importing _pyrfc: The specified module could not be found.
```

I followed the instructions.: http://sap.github.io/PyRFC/install.html#

- SAP NW RFC SDK is already installed, seems to be ok
![image](https://user-images.githubusercontent.com/46939197/70922943-44e6a100-2027-11ea-97af-42c89ce85de4.png)
- set the environment variables
C:\Users\...\nwrfcsdk
C:\Users\...\nwrfcsdk\lib
%PATH%
SAPNWRFC_HOME = C:\Users\...\nwrfcsdk
- installed latest assets from here https://github.com/SAP/PyRFC/releases/tag/2.0.1 in my virtual environment
![image](https://user-images.githubusercontent.com/46939197/70923554-52e8f180-2028-11ea-8f1c-0f2b0b7dd3ba.png)
- checked the environment variables
C:\Users\...\Python38
C:\Users\...\Python38\Scripts

I did this with Python 3.7.5 and Python 3.8 and with two different assets: pyrfc-2.0.0-cp38-cp38-win_amd64.whl and pyrfc-2.0.1-cp38-cp38-win_amd64.whl. Unfortunately without success.

**Comment by giuseppecot** [comment] 2020-01-15 15:03
Hi,
i have the same problem, and i can't solve it. 
did you find a solution?

**Comment by M9T** [comment] 2020-01-15 15:12
Still open.

**Comment by spencer-uk** [comment] 2020-01-19 19:33
Hello M9T,

If are facing this problem, let's do a quick check on the basics:

1) Python/NWRFC/OS are all 64bit or all 32bit releases - this can
generate several errors. I really recommend double check this.

2) The path to load the dll is done using on line 20 - __init__.py
add_dll_directory(os.path.join(os.environ["SAPNWRFC_HOME"], "lib"))
That tells python to include the directory built above in the search,
you can always print the result of this path combination.

3) You can double check the environment variable by running:
echo %SAPNWRFC_HOME% or
findstr Patch %SAPNWRFC_HOME%\lib\sapnwrfc.dll (nwrfcsdk-version.bat)
how does it looks like? Is the file really there where it's pointing to?


4) If you are trying to run via IDE, the IDE will start the process
therefore one need to look how the IDE is running and under what
account, the environment variables should exist there too.

5) Try to copy the files and set the path to a common location and not
under the user profile, perhaps something like:
c:\sap\nwrfcsdk
make sure your user can access this folder etc.

I believe you are running currently under:
C:\Users\maebert

Item 5 should help if your IDE is running under a different user profile.

If the error persists, try including some screenshots of the result of
the echo%SAPNWRFC_HOME%
and a dir/a/s >list.txt running inside c:\sap\nwrfcsdk that list.txt
files will contain the file list plus sizes etc. Useful to double
check versions/releases.

I do not work for SAP, I am just trying to help you.

Hope this helps,

Felipe

**Comment by RobertBrachmann** [comment] 2020-02-06 09:59
Hello, same problem here.

Windows 10 (64-bit)
Python 3.8 (64-bit)
pyrfc-2.0.1-cp38-cp38-win_amd64.whl

The environment variables seem to be ok.

L:\>echo %SAPNWRFC_HOME%
c:\nwrfcsdk

L:\>findstr Patch %SAPNWRFC_HOME%\lib\sapnwrfc.dll
750 Patch Level 3

L:\>C:\nwrfcsdk\bin\rfcexec.exe
Error: Not all mandatory parameters specified
        Please start the program in the following way:
        rfcexec -t -a <program ID> -g <gateway host> -x <gateway service>
                -f <file with list of allowed commands> -s <allowed Sys ID>
The options "-t" (trace), "-f" and "-s" are optional.

Below further optional parameters are listed. You can find their
documentation in sapnwrfc.ini:
-on_cce <0, 1, 2> (On Character Conversion Error)
-cfit (Conversion Fault Indicator Token - the substitute symbol used if on_cce=2)
-keepalive (Sets the keepalive option. Default is 0.)
-delta <0, 1> (default 1, i.e. use delta-manager)
-no_compression (table compression, default is 0, i.e. compression is on)


Could that be a Windows 10 problem?
I also reinstalled Visual C++ Redistributable Packages.

Any suggestions?

**Comment by aeRaRe** [comment] 2020-02-15 04:17
This just happened to me a few hours ago, after some troubleshooting at least in my case was fixed after I re-downloaded the SAP SDK making sure I was downloading the Windows version 

![image](https://user-images.githubusercontent.com/54864286/74581671-a9bf6880-4f90-11ea-81f2-c0d5705db142.png)

And not the AIX 64 version that set as default 
![image](https://user-images.githubusercontent.com/54864286/74581680-c2c81980-4f90-11ea-9e60-3e900942969e.png)

I compiled on my own the pyrfc wheel just in case and it worked.

**Comment by asdasdaus** [comment] 2020-02-19 20:17
> This just happened to me a few hours ago, after some troubleshooting at least in my case was fixed after I re-downloaded the SAP SDK making sure I was downloading the Windows version
> 
> ![image](https://user-images.githubusercontent.com/54864286/74581671-a9bf6880-4f90-11ea-81f2-c0d5705db142.png)
> 
> And not the AIX 64 version that set as default
> ![image](https://user-images.githubusercontent.com/54864286/74581680-c2c81980-4f90-11ea-9e60-3e900942969e.png)
> 
> I compiled on my own the pyrfc wheel just in case and it worked.

Has it worked? were you able to connect ? or import pyrfc. I am still facing the same issue even after multiple installation of SAP NWRFC SDK.

Did any one tried with other version of SAP NWRFC SDK lower than 7.50

**Comment by amarvin** [comment] 2020-02-21 02:11
Same for me
Windows 10 with Python 3.7.0 and `pyrfc-2.0.1-cp37-cp37m-win_amd64.whl`
`findstr Patch %SAPNWRFC_HOME%\lib\sapnwrfc.dll` returns `721 Patch 42`

If I uninstall `pyrfc` v2.0.1 and reinstall v1.9.93 using `pyrfc-1.9.93-cp37-cp37m-win_amd64.whl`, it works even without needing env var SAPNWRFC_HOME.

**Comment by aeRaRe** [comment] 2020-02-21 13:33
> > This just happened to me a few hours ago, after some troubleshooting at least in my case was fixed after I re-downloaded the SAP SDK making sure I was downloading the Windows version
> > ![image](https://user-images.githubusercontent.com/54864286/74581671-a9bf6880-4f90-11ea-81f2-c0d5705db142.png)
> > And not the AIX 64 version that set as default
> > ![image](https://user-images.githubusercontent.com/54864286/74581680-c2c81980-4f90-11ea-9e60-3e900942969e.png)
> > I compiled on my own the pyrfc wheel just in case and it worked.
> 
> Has it worked? were you able to connect ? or import pyrfc. I am still facing the same issue even after multiple installation of SAP NWRFC SDK.
> 
> Did any one tried with other version of SAP NWRFC SDK lower than 7.50

So far so good, after that I didn't had any more troubles.

**Comment by amarvin** [comment] 2020-02-21 15:10
Duplicate of #103

**Comment by bsrdjan** [comment] 2020-03-07 04:22
Please check [Windows platform prerequisites] (https://github.com/SAP/PyRFC/blob/master/README.md#windows).

> If I uninstall pyrfc v2.0.1 and reinstall v1.9.93 using pyrfc-1.9.93-cp37-cp37m-win_amd64.whl, it works even without needing env var SAPNWRFC_HOME.

SAPNWRFC_HOME is required on Windows only, since Python 3.8

**Comment by amarvin** [comment] 2020-03-22 02:04
> Please check [Windows platform prerequisites] (https://github.com/SAP/PyRFC/blob/master/README.md#windows).
> 
> > If I uninstall pyrfc v2.0.1 and reinstall v1.9.93 using pyrfc-1.9.93-cp37-cp37m-win_amd64.whl, it works even without needing env var SAPNWRFC_HOME.
> 
> SAPNWRFC_HOME is required on Windows only, since Python 3.8

So then why would it apply for my Python 3.7? And I do have it defined, and it still doesn't work.

**Comment by amarvin** [comment] 2020-03-22 02:05
If SAP NWRFC SDK lower than 7.50 are not supported, we should remove the claim in the readme that any version of SAP NWRFC SDK can be used.

**Comment by bsrdjan** [comment] 2020-03-22 20:40
Thank you very much for the hints. The version 7.50 is indeed the minimum version required and the documentation will be updated.

SAP NW RFC SDK is backwards compatible and according to [SAP Note 1025361](https://launchpad.support.sap.com/#/notes/1025361) the 7.20 support ended on Dec 31, 2019, with 7.50 provided as a downward compatible successor.

Is the issue still open, should I test with Python 3.7 and with which SDK version?

**Comment by amarvin** [comment] 2020-03-23 18:19
Thanks @bsrdjan for reopening the Issue, and for adding the minimum version. Amazing work on this repo!

Yes, please try your tests. I'm trying to get someone with an SAP S-user account in my company to download the SAP NWRFC SDK v7.50 for me.

**Comment by bsrdjan** [comment] 2020-03-26 15:20
I could not reproduce the issue testing on:
- fresh new Windows 10, with prerequisites installed
- SAP NWRFC SDK 7.50 PL6
- the latest PyRFC version and 1.9.93
- Python 3.7.6 and 3.8.2
It could be that new feature is added after 1.9.93, not working with older NWRFC SDK, or mismatch in prerequisites.

I compared PyRFC binaries, 1.9.93 and the latest one, using `dumpbin` and found no differences.

**Comment by amarvin** [comment] 2020-03-31 02:13
I managed to get SAP NWRFC SDK 7.50 install files, installed them, and PyRFC v2.0.4 works! With the changes to the readme, I think you can close this Issue.

**Comment by bsrdjan** [comment] 2020-03-31 14:47
Thanks !

**Closed** 2020-03-31 14:47 UTC
