### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 2-3: unexpected end of data

### ISSUE THREAD

**Issue by rohitkumarsoni** [SAP/PyRFC#218] opened 2021-01-29 09:39 UTC
ERROR:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\sap.py", line 22, in <module>
    result = conn.call('RFC_READ_TABLE', QUERY_TABLE = 'TCURR', OPTIONS = options, ROWSKIPS = rowskips, ROWCOUNT = ROWS_AT_A_TIME)
  File "src\pyrfc\_pyrfc.pyx", line 423, in pyrfc._pyrfc.Connection.call
  File "src\pyrfc\_pyrfc.pyx", line 2021, in pyrfc._pyrfc.wrapResult
  File "src\pyrfc\_pyrfc.pyx", line 2100, in pyrfc._pyrfc.wrapVariable
  File "src\pyrfc\_pyrfc.pyx", line 2070, in pyrfc._pyrfc.wrapTable
  File "src\pyrfc\_pyrfc.pyx", line 2039, in pyrfc._pyrfc.wrapStructure
  File "src\pyrfc\_pyrfc.pyx", line 2285, in pyrfc._pyrfc.wrapString
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 2-3: unexpected end of data

os-windows 10
python version - 3.8.6
sap sdk - PL 7
pyrfc release - pyrfc-2.0.0-cp38-cp38-win_amd64 
How to resolve this

**Comment by rohitkumarsoni** [comment] 2021-02-03 05:55
I also tried with pyrfc 2.3.0 but getting same error

**Comment by bsrdjan** [comment] 2021-02-09 10:14
Could you please share the test script that I could run to reproduce the issue?

**Comment by rohitkumarsoni** [comment] 2021-02-10 05:41
I am sharing the code snippet which I am using from sap blogs for connection of sap and python 

`from pyrfc import Connection, ABAPApplicationError, ABAPRuntimeError, LogonError, CommunicationError
from configparser import ConfigParser
from pprint import PrettyPrinter

ASHOST='sapxxxxx'
CLIENT='x00'
SYSNR='00'
USER='XXXXXXXX'
PASSWD='XXXXXXXX'
conn = Connection(ashost=ASHOST, sysnr=SYSNR, client=CLIENT, user=USER, passwd=PASSWD)

try:
    options = [{ 'TEXT': "FCURR = 'USD'"}]
    pp = PrettyPrinter(indent=4)
    ROWS_AT_A_TIME = 10
    rowskips = 0
    while True:
        print("----Begin of Batch---")
        result = conn.call('RFC_READ_TABLE', \
                           QUERY_TABLE = 'TCURR', \
                           OPTIONS = options, \
                           ROWSKIPS = rowskips, ROWCOUNT = ROWS_AT_A_TIME)
        pp.pprint(result['DATA'])
        rowskips += ROWS_AT_A_TIME
        if len(result['DATA']) < ROWS_AT_A_TIME:
            break
            
except CommunicationError:
    print("Could not connect to server.")
    raise
except LogonError:
    print("Could not log in. Wrong credentials?")
    raise
except (ABAPApplicationError, ABAPRuntimeError):
    print("An error occurred.")
    raise`

**Comment by rohitkumarsoni** [comment] 2021-02-10 06:15
According to your answer i tried [https://github.com/SAP/PyRFC/issues/218#issuecomment-775825883](url) but getting the same error 
```
from pyrfc import Connection, ABAPApplicationError, ABAPRuntimeError, LogonError, CommunicationError
from configparser import ConfigParser
from pprint import PrettyPrinter

ASHOST='sapxxxxx'
CLIENT='x00'
SYSNR='00'
USER='XXXXXXXX'
PASSWD='XXXXXXXX'
conn = Connection(ashost=ASHOST, sysnr=SYSNR, client=CLIENT, user=USER, passwd=PASSWD)

try:
     result = conn.call('RFC_READ_TABLE', QUERY_TABLE = 'TCURR')
     print(result)

except CommunicationError:
    print("Could not connect to server.")
    raise
except LogonError:
    print("Could not log in. Wrong credentials?")
    raise
except (ABAPApplicationError, ABAPRuntimeError):
    print("An error occurred.")
    raise
```
result = conn.call('RFC_READ_TABLE', QUERY_TABLE = 'TCURR')
File "src\pyrfc_pyrfc.pyx", line 423, in pyrfc._pyrfc.Connection.call
File "src\pyrfc_pyrfc.pyx", line 2021, in pyrfc._pyrfc.wrapResult
File "src\pyrfc_pyrfc.pyx", line 2100, in pyrfc._pyrfc.wrapVariable
File "src\pyrfc_pyrfc.pyx", line 2070, in pyrfc._pyrfc.wrapTable
File "src\pyrfc_pyrfc.pyx", line 2039, in pyrfc._pyrfc.wrapStructure
File "src\pyrfc_pyrfc.pyx", line 2107, in pyrfc._pyrfc.wrapVeriable
File "src\pyrfc_pyrfc.pyx", line 2283, in pyrfc._pyrfc.wrapString
UnicodeDecodeError: 'utf-8' codec can't decode bytes 0xff in position 60: invalid start byte

**Comment by bsrdjan** [comment] 2021-02-11 12:42
Hi @rohitkumarsoni, please check my answer on SCN. If you agree we can close the issue and follow-up on SCN?

**Comment by rohitkumarsoni** [comment] 2021-02-12 05:32
I used pyrfc 2.1.0 using 

`pip install pynwrfc==2.1.0`

For windows and its working now

**Comment by bsrdjan** [comment] 2021-02-12 08:56
Thanks for the feedback. I could not reproduce and can only guess the installation method play the role here. The installation robustness will be improved in next release (see https://github.com/SAP/PyRFC/issues/220#issuecomment-777403081) . If you want let keep this issue open, until the PL8 and next PyRFC release shipped and check if that helps?

**Comment by rohitkumarsoni** [comment] 2021-02-15 14:59
Getting the same issue while using the pyrfc 2.3.0

**Comment by bsrdjan** [comment] 2021-02-15 15:11
Could you please post:

- the output of:

```shell
node -p "require('node-rfc')".environment
```

- steps how the node-rfc is installe, including the console log

**Comment by aggsol** [comment] 2021-04-21 07:49
I can confirm that I have this issues also with 2.3.0 and downgrading to 2.1.0 solved the issue.

How to reproduce:

Just create a connection with the wrong password. Open the connection. 1 in 5 runs will trigger the bug.

**Comment by bsrdjan** [comment] 2021-04-23 13:50
Could not reproduce but please with SDK PL8 and PyRFC 2.4.0:

`pip install pyrfc` (package name changed)

**Closed** 2021-12-08 06:36 UTC
Labels: enhancement, question
