### ISSUE TITLE
pyrfc._exception.ExternalRuntimeError: RFC_BUFFER_TOO_SMALL (rc=23)

### ISSUE THREAD

**Issue by oliverzgy** [SAP/PyRFC#7] opened 2015-04-30 03:23 UTC
File "_pyrfc.pyx", line 368, in pyrfc._pyrfc.Connection.call (pyrfc\_pyrfc.c:4006)
  File "_pyrfc.pyx", line 1837, in pyrfc._pyrfc.wrapResult (pyrfc\_pyrfc.c:19400)
  File "_pyrfc.pyx", line 1910, in pyrfc._pyrfc.wrapVariable (pyrfc\_pyrfc.c:19954)
  File "_pyrfc.pyx", line 1882, in pyrfc._pyrfc.wrapTable (pyrfc\_pyrfc.c:19732)
  File "_pyrfc.pyx", line 1855, in pyrfc._pyrfc.wrapStructure (pyrfc\_pyrfc.c:19609)
  File "_pyrfc.pyx", line 1917, in pyrfc._pyrfc.wrapVariable (pyrfc\_pyrfc.c:20034)
  File "_pyrfc.pyx", line 2046, in pyrfc._pyrfc.wrapString (pyrfc\_pyrfc.c:21820)
pyrfc._exception.ExternalRuntimeError: RFC_BUFFER_TOO_SMALL (rc=23): key=RFC_BUFFER_TOO_SMALL, message= [MSG: class=, type=, number=, v1-4:=;;;]

It's 1st time to us to use this lib to communicate with sap. Hope that we can explain how it can be reproduced - 

 1. a sap char field with length 8. If this field filled with >4 Chinese characters
 2. in the rfc code, we also specify this field length to 8

The error will happen. 

Temp fix: in the rfc code, specify the length to sap_char_field_length * 2 + 1

**Comment by bsrdjan** [comment] 2015-04-30 16:25
Hi Oliver,

glad you found this issue and suggested the fix in the right direction. Please let me try to explain the cause and one quick fix, if urgent solution needed. 

The cause are these two llines, at the bottom of [_pyrfc.pyx](https://github.com/SAP/PyRFC/blob/master/pyrfc/_pyrfc.pyx) source code, starting at line 2042:
```python
cdef unsigned utf8_size = length * 2
cdef char *utf8 = <char*> malloc(utf8_size + 1)
```
Here 2 bytes are allocated per 1 unicode character, what seem to be enough for European family of languages. In Chinese family of languages there are unicode characters with 3 or more bytes and I am not sure what the optimal value here should be.

This code shows how it should be fixed, by allocating 3 bytes per character and it works for this string 四周远处都能望见 for example:

```python
cdef unsigned utf8_size = length * 3 + 1
cdef char *utf8 = <char*> malloc(utf8_size)
```
If you need a quick fix, you could build the PyRFC from source, with this correction.

This fix is not 100% solution because unicode characters may have more than 3 bytes per character (not sure if in Chinese language?). In that case the value could be increased to 4 or even more. Increasing the value increases the RAM memory consumption and 3 or more bytes allocated for every character.

I plan to move this value in [Connection configuration](http://sap.github.io/PyRFC/client.html?highlight=rstrip#configuration-of-a-connection), so that users can override the default value.

The default I would set to 3, if that enough for Chinese, feedback on that welcome.

Kind regards,
srdjan

**Comment by oliverzgy** [comment] 2016-01-07 04:08
Thank you so much, srdjan. The issue is fixed in your latest release.

**Closed** 2016-03-30 17:40 UTC

**Comment by devilsbibble** [comment] 2017-03-01 05:12
Could I ask how to solve this problem?

**Comment by bsrdjan** [comment] 2017-03-01 10:28
in latest release, 3 bytes are allocated per unicode char. If that not enough, set 4 bytes in wrapString method and compile from source:

```python
cdef unsigned utf8_size = length * 4 + 1
```

**Comment by devilsbibble** [comment] 2017-03-01 10:40
Sorry, how to compile?~

**Comment by devilsbibble** [comment] 2017-03-01 10:43
conn.get_function_description(func_name)
  File "_pyrfc.pyx", line 298, in pyrfc._pyrfc.Connection.get_function_description (pyrfc\_pyrfc.c:3471)
  File "_pyrfc.pyx", line 1777, in pyrfc._pyrfc.wrapFunctionDescription (pyrfc\_pyrfc.c:19079)
  File "_pyrfc.pyx", line 2017, in pyrfc._pyrfc.wrapString (pyrfc\_pyrfc.c:21704)
pyrfc._exception.ExternalRuntimeError: RFC_BUFFER_TOO_SMALL (rc=23): key=RFC_BUFFER_TOO_SMALL, message= [MSG: class=, type=, number=, v1-4:=;;;]

**Comment by bsrdjan** [comment] 2017-03-01 10:50
prerequisites are in README:

- SAP NW RFC Lib [Linux and Windows]
- Microsoft Visual Studio Code redistributable [Windows]

Here is the full build from source guide: http://sap.github.io/PyRFC/build.html and the short version:

```shell
git clone  https://github.com/SAP/PyRFC
python setup.py bdist_wheel
pip install dist/pyrfc-1.9.6-cp27-cp27mu-linux_x86_64.whl
```

**Comment by devilsbibble** [comment] 2017-03-02 02:58
`cdef unsigned utf8_size = uclen * 5 + 1`
when I set to 5,this error is going to happen,
`
  File "_pyrfc.pyx", line 338, in pyrfc._pyrfc.Connection.call (pyrfc\_pyrfc.c:3837)
  File "_pyrfc.pyx", line 1808, in pyrfc._pyrfc.wrapResult (pyrfc\_pyrfc.c:19284)
  File "_pyrfc.pyx", line 1881, in pyrfc._pyrfc.wrapVariable (pyrfc\_pyrfc.c:19838)
  File "_pyrfc.pyx", line 1853, in pyrfc._pyrfc.wrapTable (pyrfc\_pyrfc.c:19616)
  File "_pyrfc.pyx", line 1826, in pyrfc._pyrfc.wrapStructure (pyrfc\_pyrfc.c:19493)
  File "_pyrfc.pyx", line 1888, in pyrfc._pyrfc.wrapVariable (pyrfc\_pyrfc.c:19918)
  File "_pyrfc.pyx", line 2017, in pyrfc._pyrfc.wrapString (pyrfc\_pyrfc.c:21704)
pyrfc._exception.ExternalRuntimeError: RFC_BUFFER_TOO_SMALL (rc=23): key=RFC_BUFFER_TOO_SMALL, message= [MSG: class=, type=, number=, v1-4:=;;;]
`

**Comment by devilsbibble** [comment] 2017-03-02 03:02
Could some one help me?

**Comment by devilsbibble** [comment] 2017-03-02 04:34
@bsrdjan Could you help me solving this problem?

**Comment by bsrdjan** [comment] 2017-03-02 07:12
On which platform the issue occurs, which pyrfc version ? Can you post the script to reproduce ?

**Comment by devilsbibble** [comment] 2017-03-02 08:11
`pyrfc-1.9.5-py2.7-win32`
script is simple,but the server is in Intranet
`
from pyrfc import *
import datetime
paras = {'ashost':'X.X.X.X', 'sysnr':'00', 'client':'800', 'user':'X', 'passwd':'X'}
config = {'rstrip':True}
conn = Connection(config ,**paras)
func_name = 'ZFM_DQ_GETECDATA_HZ'
conn.get_function_description(func_name) #error here
result = conn.call(func_name , REQUTEXT=u'Hello SAP!')
print result
d = '20170301'
d = datetime.datetime.strptime(d,'%Y%m%d')
paras = {'IV_DATUM':d,'IV_WERKS':'HUA1','IV_LGORT':'Y001','IV_TYPE':'01'}
conn.call(func_name,**paras)#and error here
conn.close()

`

**Comment by bsrdjan** [comment] 2017-03-02 08:17
Could you please post the signature of the ABAP RFC, just of the parameters used in script, would be enough for testing.

**Comment by devilsbibble** [comment] 2017-03-02 08:31
What is the signature of the ABAP RFC,
`paras = {'ashost':'10.5.113.125', 'sysnr':'00', 'client':'800', 'user':'SZNMM028', 'passwd':'123456'}`
this?

**Comment by bsrdjan** [comment] 2017-03-02 08:34
sorry, I meant datatypes of RFC parameters on ABAP side. You can open the ZFM_DQ_GETECDATA_HZ in ABAP transaction SE37, open IMPORT parameters and copy as text or make a screenshot.

**Comment by devilsbibble** [comment] 2017-03-02 08:41
input:
![image](https://cloud.githubusercontent.com/assets/1435812/23499414/f8146346-ff66-11e6-89f4-1ae6c043f239.png)
?

**Comment by devilsbibble** [comment] 2017-03-02 08:43
Output:
![image](https://cloud.githubusercontent.com/assets/1435812/23499502/5aaa2dd8-ff67-11e6-89bd-6365078a556b.png)

**Comment by devilsbibble** [comment] 2017-03-02 09:39
How can i know the build success?when i change:
`cdef unsigned utf8_size = uclen * 4 + 1`

**Comment by bsrdjan** [comment] 2017-03-02 10:12
if no errors in console, the new wheel (egg) is created in the `dist` folder. That one shall be installed via:

```shell
pip uninstall pyrfc
pip install dist/pyrfc-1.9.6-cp27-cp27mu-linux_x86_64.whl
```

**Comment by devilsbibble** [comment] 2017-03-02 10:15
If so ,the build is success,but I print something in _pyrfc.pyx , the console does not show?

**Comment by devilsbibble** [comment] 2017-03-02 10:58
Thank you @bsrdjan  very much, I solved this problem, the reason is that when i reinstall the rebuild version the source is not replaced. I should:
```pip uninstall pyrfc
pip install dist/pyrfc-1.9.6-cp27-cp27mu-linux_x86_64.whl ```

**Comment by bsrdjan** [comment] 2017-03-02 11:00
or with `pip install --upgrade dist/...`, does the same. In case of new bug(s), you may open a new issue.

**Comment by devilsbibble** [comment] 2017-03-03 02:07
Ok,thanks!

**Comment by Pentusha** [comment] 2017-03-03 14:53
Hello
I've changed utf-8_size, but still got an error:
```python
cdef unsigned utf8_size = uclen * 10 + 1
```

```python
connection = pyrfc.Connection(**connection_info)
response = connection.call('ZHHDEMO_BASESCALARS', IM_SCALAR_C=u'\U0001F4AA')
```

```python
Traceback (most recent call last):
  File "my_test/test.py", line 9, in <module>
    response = connection.call('ZHHDEMO_BASESCALARS', IM_SCALAR_C=u'\U0001F4AA')
  File "src/pyrfc/_pyrfc.pyx", line 373, in pyrfc._pyrfc.Connection.call (src/pyrfc/_pyrfc.c:4442)
    fillFunctionParameter(funcDesc, funcCont, name, value)
  File "src/pyrfc/_pyrfc.pyx", line 1543, in pyrfc._pyrfc.fillFunctionParameter (src/pyrfc/_pyrfc.c:18589)
    fillVariable(paramDesc.type, container, paramDesc.name, value, paramDesc.typeDescHandle)
  File "src/pyrfc/_pyrfc.pyx", line 1587, in pyrfc._pyrfc.fillVariable (src/pyrfc/_pyrfc.c:19167)
    cValue = fillString(value)
  File "src/pyrfc/_pyrfc.pyx", line 1722, in pyrfc._pyrfc.fillString (src/pyrfc/_pyrfc.c:20988)
    raise wrapError(&errorInfo)
pyrfc._exception.ExternalRuntimeError: RFC_BUFFER_TOO_SMALL (rc=23): key=RFC_BUFFER_TOO_SMALL, message= [MSG: class=, type=, number=, v1-4:=;;;]
```

**Comment by inviscid** [comment] 2017-10-30 19:15
This still seems to be an issue.  We are getting an identical failure mode with latest release.  There appears to be an open PR for this but not sure if it is an acceptable approach:  https://github.com/SAP/PyRFC/pull/10
